"""create artifact feedback events table

Revision ID: f938bb597dcc
Revises: 481b01b23f23
Create Date: 2026-04-23 20:17:01.259591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f938bb597dcc'
down_revision: Union[str, Sequence[str], None] = '481b01b23f23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifact_feedback_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generated_artifact_id', sa.Integer(), nullable=False),
    sa.Column('feedback_type', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_artifact_id'], ['generated_artifacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifact_feedback_events_generated_artifact_id'), 'artifact_feedback_events', ['generated_artifact_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artifact_feedback_events_generated_artifact_id'), table_name='artifact_feedback_events')
    op.drop_table('artifact_feedback_events')
    # ### end Alembic commands ###
